/* Kompaktný set bežných emoji pre `:` autocomplete. n=názov, c=znak, k=kľúčové slová.
   Vkladá sa Unicode → round-tripuje ako čistý text (žiadny server, GDPR OK). */
export var EMOJI = [
  { n: 'smile', c: '😄', k: 'happy joy' },
  { n: 'grinning', c: '😀', k: 'happy' },
  { n: 'laughing', c: '😆', k: 'haha' },
  { n: 'joy', c: '😂', k: 'lol tears' },
  { n: 'rofl', c: '🤣', k: 'lol' },
  { n: 'wink', c: '😉', k: '' },
  { n: 'blush', c: '😊', k: 'happy' },
  { n: 'slightly_smiling', c: '🙂', k: 'smile' },
  { n: 'thinking', c: '🤔', k: 'hmm' },
  { n: 'neutral', c: '😐', k: 'meh' },
  { n: 'grimacing', c: '😬', k: '' },
  { n: 'sweat_smile', c: '😅', k: 'phew' },
  { n: 'cry', c: '😢', k: 'sad tear' },
  { n: 'sob', c: '😭', k: 'sad cry' },
  { n: 'angry', c: '😠', k: 'mad' },
  { n: 'rage', c: '😡', k: 'mad' },
  { n: 'sunglasses', c: '😎', k: 'cool' },
  { n: 'scream', c: '😱', k: 'shock' },
  { n: 'confused', c: '😕', k: '' },
  { n: 'sleeping', c: '😴', k: 'tired' },
  { n: 'nerd', c: '🤓', k: 'glasses' },
  { n: 'party_face', c: '🥳', k: 'celebrate' },
  { n: 'exploding_head', c: '🤯', k: 'mind blown' },
  { n: 'heart', c: '❤️', k: 'love' },
  { n: 'broken_heart', c: '💔', k: '' },
  { n: 'thumbsup', c: '👍', k: 'ok yes +1 like' },
  { n: 'thumbsdown', c: '👎', k: 'no -1 dislike' },
  { n: 'ok_hand', c: '👌', k: 'okay' },
  { n: 'clap', c: '👏', k: 'applause' },
  { n: 'wave', c: '👋', k: 'hello hi bye' },
  { n: 'pray', c: '🙏', k: 'thanks please' },
  { n: 'muscle', c: '💪', k: 'strong' },
  { n: 'point_right', c: '👉', k: '' },
  { n: 'raised_hands', c: '🙌', k: 'yay' },
  { n: 'fire', c: '🔥', k: 'lit hot' },
  { n: 'rocket', c: '🚀', k: 'launch ship' },
  { n: 'tada', c: '🎉', k: 'party celebrate' },
  { n: 'sparkles', c: '✨', k: 'shiny new' },
  { n: 'star', c: '⭐', k: 'favorite' },
  { n: 'boom', c: '💥', k: 'explosion' },
  { n: 'zap', c: '⚡', k: 'fast lightning' },
  { n: 'bulb', c: '💡', k: 'idea' },
  { n: 'check', c: '✅', k: 'done ok yes tick' },
  { n: 'x', c: '❌', k: 'no cross wrong' },
  { n: 'warning', c: '⚠️', k: 'caution' },
  { n: 'question', c: '❓', k: '' },
  { n: 'exclamation', c: '❗', k: 'important' },
  { n: 'no_entry', c: '⛔', k: 'stop block' },
  { n: 'eyes', c: '👀', k: 'look watch' },
  { n: 'bug', c: '🐛', k: 'issue defect' },
  { n: 'wrench', c: '🔧', k: 'fix tool' },
  { n: 'hammer', c: '🔨', k: 'build' },
  { n: 'lock', c: '🔒', k: 'secure' },
  { n: 'key', c: '🔑', k: '' },
  { n: 'pushpin', c: '📌', k: 'pin note' },
  { n: 'calendar', c: '📅', k: 'date' },
  { n: 'clock', c: '🕒', k: 'time' },
  { n: 'hourglass', c: '⏳', k: 'wait' },
  { n: 'chart_up', c: '📈', k: 'growth' },
  { n: 'chart_down', c: '📉', k: 'decline' },
  { n: 'memo', c: '📝', k: 'note write' },
  { n: 'clipboard', c: '📋', k: 'list' },
  { n: 'email', c: '📧', k: 'mail' },
  { n: 'phone', c: '📱', k: 'mobile' },
  { n: 'computer', c: '💻', k: 'laptop' },
  { n: 'package', c: '📦', k: 'box release' },
  { n: 'money', c: '💰', k: 'cash' },
  { n: 'green_circle', c: '🟢', k: 'ok status' },
  { n: 'yellow_circle', c: '🟡', k: 'warning status' },
  { n: 'red_circle', c: '🔴', k: 'error status' },
  { n: 'hundred', c: '💯', k: '100 perfect' },
  { n: 'wave_hand', c: '👋', k: 'hi' }
];
